environment:
  matrix:
    - nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version x64
  - node --version
  - yarn --version
  - yarn install

cache:
  - node_modules
  - .eslintcache

test_script:
  - yarn run build
  - yarn run test

# Don't actually build.
build: off

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
